### ISSUE TITLE
Touch Device: page does not scroll when carousel is in View Port

### ISSUE THREAD

**Issue by pankaj-onerent** [leandrowd/react-responsive-carousel#60]
On mobile device when we want to scroll the page and viewport has carousel then it does not allow to scroll the page.

**Comment by leandrowd** [comment]
Hi @pankaj-onerent, I just published a new version solving this problem. Check it out: https://www.npmjs.com/package/react-responsive-carousel

Demo available at http://react-responsive-carousel.js.org/

**Comment by pankaj-onerent** [comment]
@leandrowd Thanks for trying to solve this issue. But still it does not solved 100%. It's allow to scroll only half of the time.

**Comment by leandrowd** [comment]
Hi @pankaj-onerent, I've published 3.0.20 with a new prop called `swipeScrollTolerance`. Default is 5 but if you increase this number it will make it more tolerant to the swipe movement when you want to scroll. Play with this number and see if it works for you. 

The demo is updated as well (with the default value)
