### ISSUE TITLE
On swiping thumbs in mobile view losing thumbs from the page

### ISSUE THREAD

**Issue by Aagam-Jain-113** [leandrowd/react-responsive-carousel#650]
- On desktop, it works perfectly fine but there is an issue when I am shifting to mobile. 
- On Mobile, I am losing swiping left and if I swipe more after the thumbnails are finished it gets swiped and the entire thumb line just disappears as if there are more thumbs ahead.
- Technology : React

**Comment by willashe** [comment]
@Aagam-Jain-113 FYI, I was having the same problem but it appears to be fixed in v3.2.21

**Comment by Aagam-Jain-113** [comment]
Thank you @willashe. My problem has been resolved.

**Comment by GilAkivaWebiya** [comment]
@leandrowd 
This still happens on v.3.2.23 

Playground: https://codesandbox.io/s/friendly-fast-ihpkkd?file=/src/App.js


As you'll see, this also reproduces on mobile (play it @ x0.5 to better see the issue):

https://user-images.githubusercontent.com/105587970/180848904-fbbdc852-d1bc-4181-8231-7605fc31a236.mp4

**Comment by silicakes** [comment]
This has probably something to do with the infinity scroll as removing it prevents the issue from happening.
